Factory/Models/Engineer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace Factory.Models
{
  public class Engineer
  {
    public int EngineerId { get; set; }
   
    [Required(ErrorMessage = "The textbox can't be empty!")]
    public string EngineerName { get; set; }

    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:M/d/yyyy}")]
    public DateTime HireDate { get; set; }

    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Models/EngineerMachine.cs
using System.Collections.Generic;
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public int MachineId { get; set; }
    public Engineer Engineer { get; set; }
    public Machine Machine { get; set; }



  }
}

Factory/Models/EnginnerMachine.cs
using System.Collections.Generic;
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public int MachineId { get; set; }
    public Engineer Engineer { get; set; }

    public Machine Machine { get; set; }



  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {

    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachines { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }
    [Required(ErrorMessage = "The textbox can't be empty!")]
    public string MachineName { get; set; }

    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }
    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)

    {
      if (!ModelState.IsValid)
      {
        ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
        return View(engineer);
      }
      else
      {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }

    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
#nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
#nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Factory/Controllers/HomeController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Machine> model = _db.Machines
                            .ToList();
      return View(model);
    }
    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
          .Include(Machine => Machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
        return View(machine);
      }
      else
      {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
#nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
#nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }
    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add Machine!</h2>

<h4>Add a machine for engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select a machine")
    @Html.DropDownList("MachineId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list of engineers", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new engineer to this app</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.EngineerName)
  @Html.TextBoxFor(model => model.EngineerName)
  <p>@Html.ValidationMessageFor(model => model.EngineerName, "",
  new { @class = "text-danger", @style = "font-weight: 600;" })</p>
  @Html.LabelFor(model => model.HireDate)
  @Html.TextBoxFor(model => model.HireDate, "{0:M/d/yyyy}",  new { @id="datepicker" })

  <input type="submit" value="Add a new engineer" class="btn btn-primary" />
}
<p>@Html.ActionLink("Show all the engineers", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer does not have any machines.</p>
}
else
{
  <h4>Machines this engineer works on:</h4>
  <ul>
  @foreach (EngineerMachine join in Model.JoinEntities)
    {
      <li>@join.Machine.MachineName</li>
      @using (Html.BeginForm("DeleteJoin", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete This Machine" />
      }
    }
  </ul>
}
<p>@Html.ActionLink("Add a machine to this engineer", "AddMachine", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Edit this engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete This Engineer", "Delete", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Back to list of engineers", "Index")</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>

<h4>Edit this Engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.LabelFor(model => model.EngineerName)
    @Html.EditorFor(model => model.EngineerName)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>List of engineers</h1>

@if (@Model.Count == 0)
{
  <h3>No Engineers have been added to application yet!</h3>
} 

@foreach (Engineer element in Model)
{
  <li>@Html.ActionLink($"{element.EngineerName}", "Details", new { id = element.EngineerId })</li>
}

@* <p>@Html.ActionLink("Add a new engineer", "Create")</p> *@

<input type="button" value="Add new engineer" onclick="location.href='@Url.Action("Create", "Engineers")'" />

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Dr. Sillystringz Factory</h1>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add Engineer!</h2>

<h4>Add Engineer to machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select a engineer")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list of machines", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add new machine to this app</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.MachineName)
  @Html.TextBoxFor(model => model.MachineName)
  <p>@Html.ValidationMessageFor(model => model.MachineName, "",
  new { @class = "text-danger", @style = "font-weight: 600;" })</p>

  <input type="submit" value="Add new machine" class="btn btn-primary" />
}
<p>@Html.ActionLink("Show all the machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)</h3>


@if (@Model.JoinEntities.Count == 0)
{
  <p>This machine does not have any engineers yet!</p>
}
else
{
  <h4>This machine has the following engineers associated with it:</h4>
  <ul>
  @foreach (EngineerMachine join in Model.JoinEntities)
    {
      <li>Engineer: @join.Engineer.EngineerName</li>
      @using (Html.BeginForm("DeleteJoin", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete This Engineer" />
      }
    }
  </ul>
}


<p>@Html.ActionLink("Add engineer to machine ", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Edit this machine ", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete This machine", "Delete", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Back to list of machines", "Index")</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.LabelFor(model => model.MachineName)
    @Html.EditorFor(model => model.MachineName)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list of machines", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>List of machines</h1>

@if (@Model.Count == 0)
{
  <h3>No machines have been added to application yet!</h3>
} 

@foreach (Machine element in Model)
{
  <li>@Html.ActionLink($"{element.MachineName}", "Details", new { id = element.MachineId })</li>
}

<p>@Html.ActionLink("Add a new machine", "Create")</p>
<p>@Html.ActionLink("Go Back Home", "Index", "Home")</p>

Factory/Views/Shared/Footer.cshtml
<div id="footer">Copyright (c) 03/17/2023 viradeth xay-ananh</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
 <head>
   <meta charset="utf-8">
   <title>Dr. Sillystringz Factory</title>
   <link
     href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
     rel="stylesheet"
     integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
     crossorigin="anonymous" />
   <link rel="stylesheet" type="text/css" href="~/css/styles.css" />
  <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css" />
 </head>


<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="@Url.Action("Index","Home")">Home</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="@Url.Action("Index","Engineers")">Engineers</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="@Url.Action("Index","Machines")">Machines</a>
    </li>

    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Contact
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="">Engineers</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
      </div>
    </li>
  </ul>
</nav>
 @RenderBody()
 @await Html.PartialAsync("Footer")
</body>
</html>